[workspace]
members = ["control_flow",
    "data_types",
    "functions",
    "guessing_game",
    "hello",
    "variables",
]
resolver="2"

[workspace.package]
version="0.1.0"
authors=["Andre Arcaina"]
