[workspace]
members = [
    "control_flow",
    "data_types",
    "functions",
    "guessing_game",
    "hello",
    "ownership",
    "references_borrowing",
    "slice_type",
    "variables",
]
resolver="2"

[workspace.package]
version="0.1.0"
authors=["Andre Arcaina"]
